epsilon <- 10e-4

data100.org <- read.csv('square100_initialtest01.csv')
data1000.org <- read.csv('square1000_initialtest01.csv')
data5000.org <- read.csv('square5000_initialtest01.csv')

data100.converge <- subset(data100.org,!is.na(data100.org$logL.1))
data1000.converge <- subset(data1000.org,!is.na(data1000.org$logL.1))
data5000.converge <- subset(data5000.org,!is.na(data5000.org$logL.1))

data100.converge.num <- nrow(data100.converge)
data1000.converge.num <- nrow(data1000.converge)
data5000.converge.num <- nrow(data5000.converge)

data100.global <- subset(data100.converge,data100.converge$logL.1 + epsilon >= max(data100.converge$logL.1,na.rm=T))
data1000.global <- subset(data1000.converge,data1000.converge$logL.1 + epsilon >= max(data1000.converge$logL.1,na.rm=T))
data5000.global <- subset(data5000.converge,data5000.converge$logL.1 + epsilon >= max(data5000.converge$logL.1,na.rm=T))

data100.global.num <- nrow(data100.global)
data1000.global.num <- nrow(data1000.global)
data5000.global.num <- nrow(data5000.global)

data100.converge.formelt <- data.frame(data100.converge$step)
colnames(data100.converge.formelt) <- c('step')
data100.converge.formelt$from <- rep('100',nrow(data100.converge.formelt))
data1000.converge.formelt <- data.frame(data1000.converge$step)
colnames(data1000.converge.formelt) <- c('step')
data1000.converge.formelt$from <- rep('1000',nrow(data1000.converge.formelt))
data5000.converge.formelt <- data.frame(data5000.converge$step)
colnames(data5000.converge.formelt) <- c('step')
data5000.converge.formelt$from <- rep('5000',nrow(data5000.converge.formelt))
data.converge.formelt <- rbind(data100.converge.formelt, data1000.converge.formelt, data5000.converge.formelt)
data.converge.formelt$from <- factor(data.converge.formelt$from)
data.converge.lm <- lm(step~from,data=data.converge.formelt)
plot(data.converge.lm)
data.converge.aov <- aov(step~from,data=data.converge.formelt)
anova(data.converge.lm)
data.converge.kw <- kruskal.test(step~from,data=data.converge.formelt)
TukeyHSD(data.converge.aov)
plot(TukeyHSD(data.converge.aov))

data100.global.formelt <- data.frame(data100.global$step)
colnames(data100.global.formelt) <- c('step')
data100.global.formelt$from <- rep('100',nrow(data100.global.formelt))
data1000.global.formelt <- data.frame(data1000.global$step)
colnames(data1000.global.formelt) <- c('step')
data1000.global.formelt$from <- rep('1000',nrow(data1000.global.formelt))
data5000.global.formelt <- data.frame(data5000.global$step)
colnames(data5000.global.formelt) <- c('step')
data5000.global.formelt$from <- rep('5000',nrow(data5000.global.formelt))
data.global.formelt <- rbind(data100.global.formelt, data1000.global.formelt, data5000.global.formelt)
data.global.formelt$from <- factor(data.global.formelt$from)
data.global.lm <- lm(step~from,data=data.global.formelt)
plot(data.global.lm)
data.global.aov <- aov(step~from,data=data.global.formelt)
anova(data.global.lm)
TukeyHSD(data.global.aov)
plot(TukeyHSD(data.global.aov))

data.global.re <- data.global.formelt[c(-144,-344,-365),]
data.global.re.lm <- lm(step~from,data=data.global.re)
data.global.re.aov <- aov(step~from,data=data.global.re)
anova(data.global.re.lm)
data.global.re.kw <- kruskal.test(step~from,data=data.global.re)
